### ISSUE TITLE
simple inference ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [ZhengPeng7/GCoNet_plus#6]
I want to make simple inference for some images I have and the results are bad

```python

from models.GCoNet import GCoNet
import torch
from pathlib import Path
from torchvision.io import read_image
from torchvision.utils import make_grid, save_image
from torchvision import transforms

dataset_path = Path("/path/to/data")

device = torch.device("cuda")
model = GCoNet()
model = model.to(device)
gconet_dict = torch.load("/path/to/weights")
# gconet_dict = torch.load("/shared_volume/rashad/salient_app/ultimate.pth")
trans = transforms.Compose([
            transforms.Resize((320, 320)),
            # transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

model.to(device)
model.load_state_dict(gconet_dict)

model.eval()
images = [read_image(str(img_path))[None, ...] for img_path in dataset_path.glob("11/*")]
# print(images)
torch_images = torch.concat(images).float()
torch_images = trans(torch_images)
print(torch_images.shape)
with torch.no_grad():
    result = model(torch_images.cuda())[-1]
    result = torch.concat([torch.nn.functional.interpolate(res.unsqueeze(0), size=(res.shape[1], res.shape[2]), mode='bilinear', align_corners=True) for res in result]).sigmoid()
result = (result > result.mean()).float() * 255
print(result.shape)
print(result.max(), result.min())
save_image(make_grid(result), "salient_example.png")
```

And this is the result,
![salient_example](https://user-images.githubusercontent.com/26205298/192274795-7834b181-0ecf-4bb8-a624-dc21a0cf715b.png)

@HzFu @ZhengPeng7

**Comment by ZhengPeng7** [comment]
Hi Mohamed, can you provide the raw images for me?
I'll use your inference codes here to make a test on images of both CoCA and your images.
@MohamedAliRashad

**Comment by MohamedAliRashad** [comment]
They are standard JPG images, this is an example @ZhengPeng7 

![_DSC0250](https://user-images.githubusercontent.com/26205298/192307720-d7a9f10f-360e-4ec9-a664-21df69e4d17f.JPG)

**Comment by ZhengPeng7** [comment]
Yeah, but I mean... can you give me some group of images? Since it's co-sod, the number of images in one group does affect the predictions.

**Comment by MohamedAliRashad** [comment]
They are very simple and intuitive images to salient through them, @ZhengPeng7 

![_DSC0250](https://user-images.githubusercontent.com/26205298/192316882-fe4cda4a-52d5-40ba-a767-b5decf9cb886.JPG)
![_DSC0251](https://user-images.githubusercontent.com/26205298/192316889-f9d96aee-522f-4afc-b500-61db02f057b9.JPG)
![_DSC0252](https://user-images.githubusercontent.com/26205298/192316894-b522ff37-3113-4ad7-80ba-53e20dd1874f.JPG)
![_DSC0253](https://user-images.githubusercontent.com/26205298/192316898-ba3d300e-db00-44db-8088-3ada21b763fd.JPG)
![_DSC0254](https://user-images.githubusercontent.com/26205298/192316901-0c95064e-d259-435d-ac3e-551d74db3aa5.JPG)

**Comment by ZhengPeng7** [comment]
Hi Mohamed, I made my inferene code on the colab online with the `ultimate.pth`, including one group of CoCA (accordion) and the group you gave (kettle). Here are the screenshots of the colab.
![image](https://user-images.githubusercontent.com/25921713/192343317-4e17f065-87d9-402a-b5c9-bc960fca4fdc.png)
![image](https://user-images.githubusercontent.com/25921713/192343703-ce0db791-8153-4702-ac9e-eaa11c4b3146.png)


I still have some other urgent task nearly finished but not yet. So I will polish up my colab tomorrow for anyone to do the inference by our model online. Welcome to visit it.

By the way, if you want to use our model for general co-sod on images outside the available datasets, we recommend you to use the `ultimate_duts_cocoseg (The best one).pth` [here](https://drive.google.com/drive/folders/1ozJ5cgcPv8N9BjRL3AvYdekLIiPGkva9), since it is trained by two datasets.

Maybe there is something mistaken in your inference codes, you can give it a double check or just wait for my updates on colab :)

**Comment by MohamedAliRashad** [comment]
I think the problem is in the preprocessing, but I am not sure where.
If you could add the colab notebook I will be thankful
@ZhengPeng7

**Comment by ZhengPeng7** [comment]
Hi, Mohamed,
Sorry that I forgot this for days...😂
I just polish the processing of my codes in colab.

**_You can [have a try on the colab-demo](https://colab.research.google.com/drive/1nD8xm9DGPJEz1Xv7LQywyuzPQsIlkqxQ#scrollTo=EtqSWqopx27R) now._**

I've checked it, the predicted results are exactly the same as what I show in README and uploaded to google-drive.

Hope this help you. And any new question, just comment.

**Comment by MohamedAliRashad** [comment]
@ZhengPeng7 To come late is better than not coming at all.
Thanks for your efforts, I will close the issue now.
